import { HROverview, AIInsight } from '../types';

const hrInsights: AIInsight[] = [
  {
    id: 'hr-1',
    type: 'prediction',
    module: 'hr',
    title: 'Risiko Karyawan Resign Terdeteksi',
    description: 'AI mengidentifikasi 3 karyawan berkinerja tinggi dengan risiko 72% untuk resign dalam 60 hari berdasarkan pola keterlibatan, frekuensi lembur, dan perbandingan gaji pasar.',
    impact: 'high',
    confidence: 0.84,
    timestamp: '2026-04-02T08:00:00Z',
    actionable: true,
    action: 'Tinjau strategi retensi',
  },
  {
    id: 'hr-2',
    type: 'recommendation',
    module: 'hr',
    title: 'Saran Restrukturisasi Tim',
    description: 'Produktivitas tim teknik dapat meningkat 18% dengan menyeimbangkan beban kerja. 2 senior kurang dimanfaatkan sementara 3 junior kelebihan beban.',
    impact: 'medium',
    confidence: 0.76,
    timestamp: '2026-04-01T16:00:00Z',
    actionable: true,
    action: 'Lihat analisis tim',
  },
  {
    id: 'hr-3',
    type: 'alert',
    module: 'hr',
    title: 'Hambatan Perekrutan',
    description: 'Rata-rata waktu perekrutan meningkat menjadi 42 hari (naik dari 28 hari). Tahap penyaringan memiliki penundaan terlama. Pertimbangkan penyaringan resume berbantuan AI.',
    impact: 'medium',
    confidence: 0.91,
    timestamp: '2026-04-01T10:00:00Z',
    actionable: true,
    action: 'Optimalkan alur perekrutan',
  },
];

const avatarColors = ['#10b981', '#f59e0b', '#8b5cf6', '#f43f5e', '#06b6d4', '#6366f1'];

export const hrData: HROverview = {
  totalEmployees: 87,
  avgPerformance: 78,
  openPositions: 5,
  turnoverRate: 8.5,
  attendanceRate: 94.2,
  departmentDistribution: [
    { name: 'Teknik/IT', value: 28, color: '#10b981' },
    { name: 'Penjualan', value: 18, color: '#f43f5e' },
    { name: 'Pemasaran', value: 12, color: '#8b5cf6' },
    { name: 'Operasional', value: 11, color: '#06b6d4' },
    { name: 'Keuangan', value: 8, color: '#f59e0b' },
    { name: 'SDM', value: 5, color: '#6366f1' },
    { name: 'Dukungan', value: 5, color: '#64748b' },
  ],
  performanceTrend: [
    { month: 'Sep', score: 72, aiPrediction: 74 },
    { month: 'Okt', score: 74, aiPrediction: 75 },
    { month: 'Nov', score: 73, aiPrediction: 76 },
    { month: 'Des', score: 77, aiPrediction: 78 },
    { month: 'Jan', score: 76, aiPrediction: 79 },
    { month: 'Feb', score: 78, aiPrediction: 80 },
    { month: 'Mar', score: 80, aiPrediction: 81 },
    { month: 'Apr', score: 0, aiPrediction: 82 },
  ],
  employees: [
    { id: 'e1', name: 'Budi Santoso', email: 'budi@nexus.id', department: 'Teknik/IT', position: 'Senior Developer', hireDate: '2023-03-15', salary: 25000000, status: 'active', performanceScore: 92, aiScore: 94, avatar: avatarColors[0] },
    { id: 'e2', name: 'Siti Nurhaliza', email: 'siti@nexus.id', department: 'Pemasaran', position: 'Manajer Pemasaran', hireDate: '2022-08-01', salary: 22000000, status: 'active', performanceScore: 88, aiScore: 86, avatar: avatarColors[1] },
    { id: 'e3', name: 'Ahmad Rizki', email: 'ahmad@nexus.id', department: 'Penjualan', position: 'Kepala Penjualan', hireDate: '2023-01-10', salary: 20000000, status: 'active', performanceScore: 85, aiScore: 87, avatar: avatarColors[2] },
    { id: 'e4', name: 'Dewi Lestari', email: 'dewi@nexus.id', department: 'Teknik/IT', position: 'Tech Lead', hireDate: '2021-11-20', salary: 30000000, status: 'active', performanceScore: 95, aiScore: 96, avatar: avatarColors[3] },
    { id: 'e5', name: 'Reza Fahlevi', email: 'reza@nexus.id', department: 'Keuangan', position: 'Analis Keuangan', hireDate: '2024-02-01', salary: 15000000, status: 'probation', performanceScore: 72, aiScore: 75, avatar: avatarColors[4] },
    { id: 'e6', name: 'Maya Indah', email: 'maya@nexus.id', department: 'SDM', position: 'Manajer SDM', hireDate: '2022-05-15', salary: 21000000, status: 'active', performanceScore: 82, aiScore: 80, avatar: avatarColors[5] },
    { id: 'e7', name: 'Faisal Rahman', email: 'faisal@nexus.id', department: 'Operasional', position: 'Kepala Operasional', hireDate: '2023-06-01', salary: 19000000, status: 'active', performanceScore: 79, aiScore: 81, avatar: avatarColors[0] },
    { id: 'e8', name: 'Putri Amelia', email: 'putri@nexus.id', department: 'Teknik/IT', position: 'Junior Developer', hireDate: '2025-01-15', salary: 12000000, status: 'active', performanceScore: 68, aiScore: 73, avatar: avatarColors[1] },
    { id: 'e9', name: 'Dimas Pratama', email: 'dimas@nexus.id', department: 'Penjualan', position: 'Account Executive', hireDate: '2024-07-01', salary: 16000000, status: 'active', performanceScore: 76, aiScore: 78, avatar: avatarColors[2] },
    { id: 'e10', name: 'Laras Wulandari', email: 'laras@nexus.id', department: 'Dukungan', position: 'Customer Success', hireDate: '2024-09-01', salary: 13000000, status: 'on-leave', performanceScore: 81, aiScore: 79, avatar: avatarColors[3] },
  ],
  reviews: [
    { id: 'r1', employeeId: 'e4', employeeName: 'Dewi Lestari', period: 'Q1 2026', score: 95, aiScore: 96, strengths: ['Kepemimpinan teknis', 'Mementoring junior', 'Arsitektur sistem'], improvements: ['Keterampilan delegasi', 'Komunikasi antar tim'], recommendation: 'Siap untuk promosi ke VP Engineering. Telah secara konsisten melampaui target dan membimbing 4 anggota tim ke level senior.' },
    { id: 'r2', employeeId: 'e1', employeeName: 'Budi Santoso', period: 'Q1 2026', score: 92, aiScore: 94, strengths: ['Kualitas kode', 'Penyelesaian masalah', 'Keahlian DevOps'], improvements: ['Dokumentasi', 'Keterampilan presentasi'], recommendation: 'Performa sangat kuat. Pertimbangkan untuk peran tech lead di proyek baru. AI mencatat penyelesaian tiket 23% lebih cepat dari rata-rata tim.' },
    { id: 'r3', employeeId: 'e3', employeeName: 'Ahmad Rizki', period: 'Q1 2026', score: 85, aiScore: 87, strengths: ['Hubungan klien', 'Negosiasi', 'Manajemen pipeline'], improvements: ['Higiene data CRM', 'Akurasi prakiraan'], recommendation: 'Melampaui target penjualan sebesar 15%. AI menyarankan untuk dipasangkan dengan anggota tim baru untuk transfer pengetahuan.' },
  ],
  recruitment: [
    { id: 'rec1', position: 'Senior Frontend Developer', department: 'Teknik/IT', candidates: 45, stage: 'interview', aiTopMatch: 'Kandidat #23 - Andi S.', matchScore: 92, postedDate: '2026-03-01' },
    { id: 'rec2', position: 'Analis Data', department: 'Keuangan', candidates: 28, stage: 'screening', aiTopMatch: 'Kandidat #8 - Rina K.', matchScore: 87, postedDate: '2026-03-15' },
    { id: 'rec3', position: 'Spesialis Pemasaran', department: 'Pemasaran', candidates: 62, stage: 'open', aiTopMatch: 'Menunggu penyaringan', matchScore: 0, postedDate: '2026-03-25' },
    { id: 'rec4', position: 'DevOps Engineer', department: 'Teknik/IT', candidates: 19, stage: 'offer', aiTopMatch: 'Kandidat #5 - Hendro W.', matchScore: 95, postedDate: '2026-02-15' },
    { id: 'rec5', position: 'Customer Success Lead', department: 'Dukungan', candidates: 33, stage: 'screening', aiTopMatch: 'Kandidat #12 - Dian P.', matchScore: 84, postedDate: '2026-03-20' },
  ],
  aiInsights: hrInsights,
};
