import { InventoryOverview, AIInsight } from '../types';

const inventoryInsights: AIInsight[] = [
  {
    id: 'inv-1',
    type: 'prediction',
    module: 'inventory',
    title: 'Prediksi Lonjakan Permintaan',
    description: 'AI memprediksi kenaikan permintaan 45% untuk "Wireless Keyboard Pro" minggu depan berdasarkan pola musiman dan efek kampanye pemasaran baru-baru ini.',
    impact: 'high',
    confidence: 0.88,
    timestamp: '2026-04-02T09:00:00Z',
    actionable: true,
    action: 'Pesan 200 unit sekarang',
  },
  {
    id: 'inv-2',
    type: 'alert',
    module: 'inventory',
    title: '3 Produk di Bawah Stok Aman',
    description: 'USB-C Hub, Monitor Stand, dan Webcam HD berada di bawah level stok minimum. Pesanan otomatis telah masuk antrean menunggu persetujuan.',
    impact: 'high',
    confidence: 1.0,
    timestamp: '2026-04-02T07:00:00Z',
    actionable: true,
    action: 'Setujui permintaan pemesanan kembali',
  },
  {
    id: 'inv-3',
    type: 'recommendation',
    module: 'inventory',
    title: 'Optimasi Kelebihan Stok',
    description: 'Mouse Pad Premium memiliki 340 unit (2.8x level maks). Pertimbangkan untuk menjalankan promosi diskon 20% untuk mengurangi biaya penyimpanan Rp24 juta/bulan.',
    impact: 'medium',
    confidence: 0.82,
    timestamp: '2026-04-01T15:00:00Z',
    actionable: true,
    action: 'Buat promosi',
  },
];

export const inventoryData: InventoryOverview = {
  totalProducts: 156,
  totalValue: 2340000000, // Rp 2.34 Miliar
  lowStockCount: 12,
  outOfStockCount: 3,
  turnoverRate: 4.2,
  stockByCategory: [
    { name: 'Elektronik', value: 890000000, color: '#10b981' },
    { name: 'Aksesori', value: 520000000, color: '#06b6d4' },
    { name: 'Periferal', value: 430000000, color: '#8b5cf6' },
    { name: 'Jaringan', value: 310000000, color: '#f59e0b' },
    { name: 'Penyimpanan', value: 190000000, color: '#f43f5e' },
  ],
  demandForecast: [
    { day: 'Sen', predicted: 145, actual: 138 },
    { day: 'Sel', predicted: 162, actual: 155 },
    { day: 'Rab', predicted: 158, actual: 170 },
    { day: 'Kam', predicted: 175, actual: 168 },
    { day: 'Jum', predicted: 190, actual: 185 },
    { day: 'Sab', predicted: 210, actual: 0 },
    { day: 'Min', predicted: 195, actual: 0 },
  ],
  products: [
    { id: 'p1', name: 'Wireless Keyboard Pro', sku: 'WKP-001', category: 'Periferal', unitPrice: 890000, costPrice: 520000, currentStock: 45, minStock: 20, maxStock: 100, warehouse: 'Jakarta Pusat', status: 'in-stock' },
    { id: 'p2', name: 'USB-C Hub 7-in-1', sku: 'UCH-007', category: 'Aksesori', unitPrice: 450000, costPrice: 280000, currentStock: 8, minStock: 15, maxStock: 60, warehouse: 'Jakarta Pusat', status: 'low-stock' },
    { id: 'p3', name: 'Monitor Stand Adjustable', sku: 'MSA-012', category: 'Aksesori', unitPrice: 350000, costPrice: 195000, currentStock: 3, minStock: 10, maxStock: 40, warehouse: 'Surabaya', status: 'low-stock' },
    { id: 'p4', name: 'Webcam HD 1080p', sku: 'WHD-108', category: 'Elektronik', unitPrice: 520000, costPrice: 310000, currentStock: 0, minStock: 10, maxStock: 50, warehouse: 'Jakarta Pusat', status: 'out-of-stock' },
    { id: 'p5', name: 'Mechanical Keyboard RGB', sku: 'MKR-256', category: 'Periferal', unitPrice: 1200000, costPrice: 750000, currentStock: 67, minStock: 15, maxStock: 80, warehouse: 'Bandung', status: 'in-stock' },
    { id: 'p6', name: 'Mouse Pad Premium XL', sku: 'MPP-XL1', category: 'Aksesori', unitPrice: 150000, costPrice: 45000, currentStock: 340, minStock: 30, maxStock: 120, warehouse: 'Jakarta Pusat', status: 'overstock' },
    { id: 'p7', name: 'Ethernet Cable Cat6 5m', sku: 'EC6-005', category: 'Jaringan', unitPrice: 45000, costPrice: 18000, currentStock: 250, minStock: 50, maxStock: 300, warehouse: 'Surabaya', status: 'in-stock' },
    { id: 'p8', name: 'SSD Eksternal 1TB', sku: 'SSD-1TB', category: 'Penyimpanan', unitPrice: 1450000, costPrice: 980000, currentStock: 22, minStock: 10, maxStock: 50, warehouse: 'Jakarta Pusat', status: 'in-stock' },
    { id: 'p9', name: 'Laptop Stand Aluminum', sku: 'LSA-001', category: 'Aksesori', unitPrice: 280000, costPrice: 145000, currentStock: 5, minStock: 10, maxStock: 40, warehouse: 'Bandung', status: 'low-stock' },
    { id: 'p10', name: 'Wireless Mouse Ergonomic', sku: 'WME-002', category: 'Periferal', unitPrice: 320000, costPrice: 185000, currentStock: 58, minStock: 20, maxStock: 80, warehouse: 'Jakarta Pusat', status: 'in-stock' },
  ],
  movements: [
    { id: 'm1', productId: 'p1', productName: 'Wireless Keyboard Pro', type: 'out', quantity: 12, date: '2026-04-02', reference: 'SO-2026-089', warehouse: 'Jakarta Pusat' },
    { id: 'm2', productId: 'p5', productName: 'Mechanical Keyboard RGB', type: 'in', quantity: 30, date: '2026-04-02', reference: 'PO-2026-045', warehouse: 'Bandung' },
    { id: 'm3', productId: 'p2', productName: 'USB-C Hub 7-in-1', type: 'out', quantity: 5, date: '2026-04-01', reference: 'SO-2026-088', warehouse: 'Jakarta Pusat' },
    { id: 'm4', productId: 'p8', productName: 'SSD Eksternal 1TB', type: 'transfer', quantity: 10, date: '2026-04-01', reference: 'TR-2026-012', warehouse: 'Surabaya → Jakarta' },
    { id: 'm5', productId: 'p10', productName: 'Wireless Mouse Ergonomic', type: 'in', quantity: 25, date: '2026-03-31', reference: 'PO-2026-044', warehouse: 'Jakarta Pusat' },
    { id: 'm6', productId: 'p6', productName: 'Mouse Pad Premium XL', type: 'adjustment', quantity: -5, date: '2026-03-31', reference: 'ADJ-2026-003', warehouse: 'Jakarta Pusat' },
  ],
  reorderSuggestions: [
    { productId: 'p4', productName: 'Webcam HD 1080p', currentStock: 0, suggestedQty: 35, confidence: 0.95, reason: 'Kehabisan stok. Rata-rata penjualan harian: 2.3 unit. Waktu tunggu: 7 hari.', estimatedCost: 10850000, urgency: 'critical' },
    { productId: 'p2', productName: 'USB-C Hub 7-in-1', currentStock: 8, suggestedQty: 40, confidence: 0.88, reason: 'Di bawah stok minimum. Tren permintaan naik 15% dari bulan ke bulan.', estimatedCost: 11200000, urgency: 'high' },
    { productId: 'p3', productName: 'Monitor Stand Adjustable', currentStock: 3, suggestedQty: 25, confidence: 0.85, reason: 'Hampir habis. Rata-rata waktu tunggu dari pemasok: 10 hari.', estimatedCost: 4875000, urgency: 'high' },
    { productId: 'p9', productName: 'Laptop Stand Aluminum', currentStock: 5, suggestedQty: 20, confidence: 0.78, reason: 'Di bawah minimum. Produk dengan margin tinggi, layak untuk restock.', estimatedCost: 2900000, urgency: 'medium' },
  ],
  aiInsights: inventoryInsights,
};
